### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by JohnFTitor** [Bondok6/Green-Travel#2]
# Hi @Bondok6  👋🏻   

Your project is great Kyrillos 💯. You followed the design and added some smooth transitions which makes the project elegant

## Suggestions 🚀🚀 

- [x] The logo in the Desktop Version should take you to the home page

# Closing 😸 

Please let me know If you have any questions about my suggestions. We're all here to learn so let's take advantage of different perspectives!
Cheers and happy coding! 👨🏻‍💻 

<img src="https://media3.giphy.com/media/Q2DabV4eRh160/giphy.gif"/>

**Comment by lisandroseia** [comment]
I think that, in order to improve your code, you should fix the overlapped images in the speakers section

**Comment by Yothu** [comment]
I would recommend adding `alt` attributes values to the partner section images.

**Comment by Bondok6** [comment]
Thank you very much I will do these changes. 👌
